language: generic

addons:
  apt_packages:
  - zsh
  - ksh

before_install:
  - wget --version
  - curl --version
  - export __luaver_env="testing"

install:
  - git clone --depth 1 https://github.com/sstephenson/bats.git
  - . ./install.sh

script:
  - ./bats/bin/bats tests
  - ./tests/integration\ tests/test.sh

env:
  - SHELL=bash
  - SHELL=zsh
  - SHELL=sh
