language: generic
addons:
  apt_packages:
  - zsh
  - ksh
before_install:
  - wget --version
  - curl --version
install:
  - curl https://raw.githubusercontent.com/dhavalkapil/luaver/master/install.sh -o install.sh && . ./install.sh
script:
  - ./tests/integration/test.sh
