language: generic

addons:
  apt_packages:
  - zsh
  - ksh

before_install:
  - wget --version
  - curl --version
  - export __luaver_env="testing"

install:
  - if [[ $SHELL == bash ]]; then git clone --depth 1 https://github.com/sstephenson/bats.git; fi
  - . ./install.sh

script:
  - if [[ $SHELL == bash ]]; then ./bats/bin/bats tests; fi
  - $SHELL ./tests/integration\ tests/test.sh

env:
  - SHELL=bash
  - SHELL=zsh
  - SHELL=sh
